language: node_js
node_js:
  - 10
  - 12
cache:
  directories:
    - node_modules

before_install:
  - openssl aes-256-cbc -K $encrypted_bcfeda9310f4_key -iv $encrypted_bcfeda9310f4_iv -in inventory.enc -out inventory -d
  - openssl aes-256-cbc -K $encrypted_bcfeda9310f4_key -iv $encrypted_bcfeda9310f4_iv -in ssh_key.enc -out ssh_key -d
  
install:
  - npm install -g codecov

script:
  - npm run test:unit

after_success:
  - if [[ $TRAVIS_NODE_VERSION == 10 ]]; then codecov; fi