language: node_js
dist: bionic
node_js:
  - 10
  - 12
  - 13
cache:
  directories:
    - node_modules

before_install:
  - sudo apt update
  - sudo apt install -y ansible
  - openssl aes-256-cbc -K $encrypted_a5b4e8ef6288_key -iv $encrypted_a5b4e8ef6288_iv -in deploy/secrets.tar.enc -out deploy/secrets.tar -d
  - tar xvf deploy/secrets.tar
  
install:
  - npm install
  - npm install -g codecov

script:
  - npm run test:unit

after_success:
  - if [[ $TRAVIS_NODE_VERSION == 12 ]]; then codecov; fi

deploy:
  - provider: script
    skip_cleanup: true
    script: ./deploy/deploy
    on:
      node_js: 12
      branch: master
      tags: true