language: node_js
node_js:
  - 10
  - 12
cache:
  directories:
    - node_modules

before_install:
  - openssl aes-256-cbc -K $encrypted_a5b4e8ef6288_key -iv $encrypted_a5b4e8ef6288_iv -in secrets.tar.enc -out deploy/secrets.tar -d
  - tar xvf deploy/secrets.tar -C deploy/
  
install:
  - npm install -g codecov

script:
  - npm run test:unit

after_success:
  - if [[ $TRAVIS_NODE_VERSION == 10 ]]; then codecov; fi