trigger:
- master
- refs/tags/*

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build_test
  displayName: 'Build and test'
  jobs:
  - job: unit_test
    displayName: 'Run unit tests'
    strategy:
      matrix:
        node_10:
          node_version: '10.x'
        node_12:
          node_version: '12.x'
        node_13:
          node_version: '13.x'
      maxParallel: 3
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: $(node_version)
        displayName: 'Install Node.js'
    - script: |
        npm install
        sudo npm install -g codecov
      displayName: 'Install dependencies'
    - script: npm run test:unit
      displayName: 'Run unit tests'
    - script: codecov
      displayName: 'Upload Coverage'
      condition: and(succeeded(), eq(variables['node_version'], '12.x'))
      env:
        CODECOV_TOKEN: $(CODECOV_TOKEN)
  - job: build_docker
    displayName: 'Build docker image'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
        displayName: 'Install Node.js'
    - script: |
        npm install
        npm run build --production
      displayName: 'Install and build package'
    - script: docker build . -t ahugues/porygon-frontend
      displayName: 'Build image'
    - script: docker save -o $(Build.ArtifactStagingDirectory)/porygon-frontend.tar ahugues/porygon-frontend:latest
      displayName: 'Save image'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish image to artifacts'
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: docker_artifacts


- stage: deploy
  displayName: 'Deploy'
  condition: and(succeeded(), or(eq(variables['build.sourceBranch'], 'refs/heads/master'), startsWith(variables['build.sourceBranch'], 'refs/tags/')))
  jobs:
  - job: deploy_docker
    displayName: 'Deploy docker image'
    steps:
    - task: Docker@2
      displayName: 'Login to DockerHub'
      inputs:
        command: login
        containerRegistry: docker-hub-ahugues
    - task: DownloadBuildArtifacts@0
      displayName: 'Download image from artifacts'
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'docker_artifacts'
        downloadPath: '$(System.ArtifactsDirectory)'
    - script: docker load -i $(System.ArtifactsDirectory)/docker_artifacts/porygon-frontend.tar
      displayName: 'Load docker image'
    - script: docker tag ahugues/porygon-frontend:latest ahugues/porygon-frontend:master
      displayName: 'Tag master image'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    - task: Docker@2
      displayName: 'Push master image'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        command: push
        repository: ahugues/porygon-frontend
        containerRegistry: docker-hub-ahugues
        tags: |
          master
    - script: bash docker_push 
      displayName: 'Push tagged images to Docker Hub'
      condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
